"""shipment loop flag

Revision ID: f2797d4c4b28
Revises: c5b435ba7e82
Create Date: 2026-07-06 09:29:01.846613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2797d4c4b28'
down_revision: Union[str, Sequence[str], None] = 'c5b435ba7e82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'shipments',
        sa.Column('loop', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'loop')
    # ### end Alembic commands ###
