"""regions table

Revision ID: f7689f6fa687
Revises: 353df4e49cdf
Create Date: 2026-07-03 20:02:11.406145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision: str = 'f7689f6fa687'
down_revision: Union[str, Sequence[str], None] = '353df4e49cdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('polygon', Geography(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_regions_polygon', 'regions', ['polygon'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_regions_org_id'), 'regions', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regions_org_id'), table_name='regions')
    op.drop_geospatial_index('idx_regions_polygon', table_name='regions', postgresql_using='gist', column_name='polygon')
    op.drop_geospatial_table('regions')
    # ### end Alembic commands ###
